export const FALLBACK_EVENTS = [
  { date: "2026-02-02", name: "District Zouk Drop-in Classes & Practica", type: "class", url: "https://www.districtzouk.com/pages/monday-drop-ins" },
  { date: "2026-02-03", name: "District Zouk Progressive Zouk & Lambada Classes", type: "class", url: "https://www.districtzouk.com/pages/progressive-classes-for-brazilian-zouk" },
  { date: "2026-02-04", name: "District Zouk Practica & Assessments", type: "class", url: "https://www.districtzouk.com/pages/socials-and-events" },
  { date: "2026-02-07", name: "District Zouk Workshops and Social (Glen Echo)", type: "social", url: "https://www.districtzouk.com/pages/socials-and-events" },
  { date: "2026-02-09", name: "District Zouk Drop-in Classes & Practica", type: "class", url: "https://www.districtzouk.com/pages/monday-drop-ins" },
  { date: "2026-02-10", name: "District Zouk Progressive Zouk & Lambada Classes", type: "class", url: "https://www.districtzouk.com/pages/progressive-classes-for-brazilian-zouk" },
  { date: "2026-02-11", name: "District Zouk Progressive Zouk & Lambada Classes", type: "class", url: "https://www.districtzouk.com/pages/progressive-classes-for-brazilian-zouk" },
  { date: "2026-02-13", name: "Maison Rouge Valentines Social", type: "social", url: "" },
  { date: "2026-02-15", name: "La Cosecha Social", type: "social", url: "https://www.tickettailor.com/events/brazilianzoukpopupsocial" },
  { date: "2026-02-16", name: "District Zouk Drop-in Classes & Practica", type: "class", url: "https://www.districtzouk.com/pages/monday-drop-ins" },
  { date: "2026-02-17", name: "District Zouk Progressive Zouk & Lambada Classes", type: "class", url: "https://www.districtzouk.com/pages/progressive-classes-for-brazilian-zouk" },
  { date: "2026-02-18", name: "District Zouk Progressive Zouk & Lambada Classes", type: "class", url: "https://www.districtzouk.com/pages/progressive-classes-for-brazilian-zouk" },
  { date: "2026-02-18", name: "Born 2 Dance Brazilian Zouk & Lambada with Iago & Vanessa", type: "class", url: "https://justgo.dance/iago-vanessa-weeklyclasses" },
  { date: "2026-02-20", name: "2026 Community Welcome Social", type: "social", url: "" },
  { date: "2026-02-22", name: "District Zouk Social (Bryant St Market)", type: "social", url: "https://www.districtzouk.com/pages/socials-and-events" },
  { date: "2026-02-23", name: "District Zouk Drop-in Classes & Practica", type: "class", url: "https://www.districtzouk.com/pages/monday-drop-ins" },
  { date: "2026-02-24", name: "District Zouk Progressive Zouk & Lambada Classes", type: "class", url: "https://www.districtzouk.com/pages/progressive-classes-for-brazilian-zouk" },
  { date: "2026-02-25", name: "District Zouk Progressive Zouk & Lambada Classes", type: "class", url: "https://www.districtzouk.com/pages/progressive-classes-for-brazilian-zouk" },
  { date: "2026-02-27", name: "District Zouk Weekender - Classes & Social", type: "festival", url: "https://www.districtzouk.com/pages/socials-and-events" },
  { date: "2026-02-28", name: "District Zouk Weekender - Workshops & Social", type: "festival", url: "https://www.districtzouk.com/pages/socials-and-events" },
  { date: "2026-03-01", name: "District Zouk Weekender - Workshops", type: "festival", url: "https://www.districtzouk.com/pages/socials-and-events" },
  { date: "2026-03-02", name: "District Zouk Drop-in Classes & Practica", type: "class", url: "https://www.districtzouk.com/pages/monday-drop-ins" },
  { date: "2026-03-04", name: "Born 2 Dance Brazilian Zouk & Lambada with Iago & Vanessa", type: "class", url: "https://justgo.dance/iago-vanessa-weeklyclasses" },
  { date: "2026-03-05", name: "Brazilian Zouk Jack & Jill Training", type: "class", url: "" },
  { date: "2026-03-08", name: "District Zouk Social (Bryant St Market)", type: "social", url: "https://www.districtzouk.com/pages/socials-and-events" },
  { date: "2026-03-09", name: "District Zouk Drop-in Classes & Practica", type: "class", url: "https://www.districtzouk.com/pages/monday-drop-ins" },
  { date: "2026-03-11", name: "Born 2 Dance Brazilian Zouk & Lambada with Iago & Vanessa", type: "class", url: "https://justgo.dance/iago-vanessa-weeklyclasses" },
  { date: "2026-03-12", name: "Brazilian Zouk Jack & Jill Training", type: "class", url: "" },
  { date: "2026-03-14", name: "District Zouk Social (Glen Echo)", type: "social", url: "https://www.districtzouk.com/pages/socials-and-events" },
  { date: "2026-03-15", name: "La Cosecha Social", type: "social", url: "https://www.tickettailor.com/events/brazilianzoukpopupsocial" },
  { date: "2026-03-16", name: "District Zouk Drop-in Classes & Practica", type: "class", url: "https://www.districtzouk.com/pages/monday-drop-ins" },
  { date: "2026-03-18", name: "Born 2 Dance Brazilian Zouk & Lambada with Iago & Vanessa", type: "class", url: "https://justgo.dance/iago-vanessa-weeklyclasses" },
  { date: "2026-03-19", name: "Brazilian Zouk Jack & Jill Training", type: "class", url: "" },
  { date: "2026-03-20", name: "BZ Weekender", type: "festival", url: "" },
  { date: "2026-03-21", name: "BZ Weekender", type: "festival", url: "" },
  { date: "2026-03-22", name: "BZ Weekender", type: "festival", url: "" },
  { date: "2026-03-23", name: "District Zouk Drop-in Classes & Practica", type: "class", url: "https://www.districtzouk.com/pages/monday-drop-ins" },
  { date: "2026-03-25", name: "Born 2 Dance Brazilian Zouk & Lambada with Iago & Vanessa", type: "class", url: "https://justgo.dance/iago-vanessa-weeklyclasses" },
  { date: "2026-03-26", name: "Brazilian Zouk Jack & Jill Training", type: "class", url: "" },
  { date: "2026-03-28", name: "Maison Rouge Social", type: "social", url: "" },
  { date: "2026-03-29", name: "District Zouk Social (Bryant St Market)", type: "social", url: "https://www.districtzouk.com/pages/socials-and-events" },
  { date: "2026-03-30", name: "District Zouk Drop-in Classes & Practica", type: "class", url: "https://www.districtzouk.com/pages/monday-drop-ins" },
  { date: "2026-04-01", name: "Born 2 Dance Brazilian Zouk & Lambada with Iago & Vanessa", type: "class", url: "https://justgo.dance/iago-vanessa-weeklyclasses" },
  { date: "2026-04-02", name: "Brazilian Zouk Jack & Jill Training", type: "class", url: "" },
  { date: "2026-04-04", name: "District Zouk Workshops and Social (Glen Echo)", type: "social", url: "https://www.districtzouk.com/pages/socials-and-events" },
  { date: "2026-04-06", name: "District Zouk Drop-in Classes & Practica", type: "class", url: "https://www.districtzouk.com/pages/monday-drop-ins" },
  { date: "2026-04-09", name: "ZOUK HEAT 2026", type: "festival", url: "https://zoukheat.com/" },
  { date: "2026-04-13", name: "District Zouk Drop-in Classes & Practica", type: "class", url: "https://www.districtzouk.com/pages/monday-drop-ins" },
  { date: "2026-04-14", name: "District Zouk Progressive Zouk & Lambada Classes", type: "class", url: "https://www.districtzouk.com/pages/progressive-classes-for-brazilian-zouk" },
  { date: "2026-04-15", name: "District Zouk Progressive Zouk & Lambada Classes", type: "class", url: "https://www.districtzouk.com/pages/progressive-classes-for-brazilian-zouk" },
  { date: "2026-04-18", name: "District Zouk Workshops and Social (Glen Echo)", type: "social", url: "https://www.districtzouk.com/pages/socials-and-events" },
  { date: "2026-04-19", name: "La Cosecha Social", type: "social", url: "https://www.tickettailor.com/events/brazilianzoukpopupsocial" },
  { date: "2026-04-20", name: "District Zouk Drop-in Classes & Practica", type: "class", url: "https://www.districtzouk.com/pages/monday-drop-ins" },
  { date: "2026-04-21", name: "District Zouk Progressive Zouk & Lambada Classes", type: "class", url: "https://www.districtzouk.com/pages/progressive-classes-for-brazilian-zouk" },
  { date: "2026-04-22", name: "District Zouk Progressive Zouk & Lambada Classes", type: "class", url: "https://www.districtzouk.com/pages/progressive-classes-for-brazilian-zouk" },
  { date: "2026-04-25", name: "Maison Rouge Social", type: "social", url: "" },
  { date: "2026-04-26", name: "District Zouk Social (Bryant St Market)", type: "social", url: "https://www.districtzouk.com/pages/socials-and-events" },
];
